import React, { useState } from 'react'
import Form from '../components/Form.jsx'
import ImageCard from '../components/ImageCard'
import Loading from '../components/Loading'


function RenderCards({ data, title }) {
  if (data?.length) {
    return data.map(post => <ImageCard key={post._id} {...post} />)
  }
  return <h2 className='text-rose-700 text-xl font-bold uppercase mt-5'>{title}</h2>
}

export default function Home() {


  const [loading, setLoading] = useState(false)
  const [allPosts, setAllPosts] = useState([])
  const [searchText, setSearchText] = useState('')

  return <>
    <main className='w-full flex flex-col'>

      <h1 className='text-3xl font-extrabold pb-2'>Community Showcase</h1>
      <p className='opacity-50'>Browse a great collection of the community AI generated images that is generated by DALL-E Clone</p>

      <section className='pt-12'>
        <Form
          label="Your Name"
          type="text"
          name="name"
          placeholder="Kareem Ezzat"
          value
          handleChange
        />
      </section>

      <section className='pt-10'>
        {
          loading
            ? <div className='mt-[-30px]'><Loading /></div>
            : <div>
              {
                searchText &&
                <h2 className='text-md'>
                  Showing results for: <span className='text-rose-400'>{searchText}</span>
                </h2>
              }
              <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
                {
                  searchText
                    ? <RenderCards data={[]} title='No Results Found' />
                    : <RenderCards data={[]} title='No Posts Found' />
                }
              </div>
            </div>
        }
      </section>

    </main>
  </>
}
